env: "development"
log_level: "debug"
article_service:
  ports:
    http: "8001"
    grpc: "9000"
search_service:
  ports:
    http: "8002"
postgres:
  host: "localhost:25432"
  database: "article_service"
  username: "alpha"
  password: "irvankdhf"
  sslmode: "disable"
  max_idle_conns: 2
  conn_max_lifetime: "1h"
  ping_interval: "5000ms"
  retry_attempts: 3
redis:
  cache_host: "redis://localhost:6379/0"
  lock_host: "redis://localhost:6379/1"
  pub_sub: "redis://localhost:6379"
elasticsearch:
  timeout: "3s"
  host: "http://localhost:19200"
  set_sniff: false
  set_health_check: false
  max_idle_connections: 2
  max_conns_per_host: 10
services:
  article_target: "localhost:9000"
  idle_conn_pool: "1000"
  max_conn_pool: "2000"